### PR TITLE
add a "home", show list of incidents & show actions in incidents

### PR DESCRIPTION
**Pull request by diederich**
I "stole" this from https://github.com/influxdata/response/tree/gm/actions-in-report

It fixes mainly 3 things for us:
* having a "home" out of the box
* see a list of incidents
* see the list of actions on an incident

This looks pretty compact and self contained and might be a good starter for others as well?

### CODE REVIEW

**Comment by evnsio** [comment]
Thanks for raising this. Would you mind attaching a screenshot to the PR description please?

**Comment by diederich** [comment]
Screenshot 2020-03-15 at 22 30 33

FYI: I think the title of the incident might be outdated. Haven't looked into it yet though.

**Comment by diederich** [comment]
Sorry forgot this. Here's the list of actions that appeared :-)

Screenshot 2020-03-15 at 22 33 04

**Comment by diederich** [comment]
Thanks for looking into this, and please mind that I have only glanced over the templates etc..
(It's my first python in quite a while... 😂)

So also definitely happy to fix suggestions etc..

**Pull request merged**
